// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZwalks.Data;

#nullable disable

namespace NZwalks.Migrations
{
    [DbContext(typeof(NZwalksDbContext))]
    partial class NZwalksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZwalks.Models.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42d731f8-d04e-4633-9c4f-1a4a27500b55"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("0c306fab-d484-41fe-9a44-d6088bb75daf"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("5895a33b-fafc-4798-9688-2c609d097fe6"),
                            Name = "Difficult"
                        });
                });

            modelBuilder.Entity("NZwalks.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("176e331a-4eff-ee98-ea56-dc4a0e84757d"),
                            Code = "Lake",
                            Name = "East Madiebury",
                            RegionImageUrl = "https://loremflickr.com/320/240?lock=1020670308"
                        },
                        new
                        {
                            Id = new Guid("97930e56-f26e-611e-1820-46d1a0245995"),
                            Code = "Port",
                            Name = "West Maurineshire",
                            RegionImageUrl = "https://loremflickr.com/320/240?lock=842203058"
                        },
                        new
                        {
                            Id = new Guid("4d05aca1-c10a-5317-bfe4-8c17096cb62a"),
                            Code = "New",
                            Name = "New Darwin",
                            RegionImageUrl = "https://loremflickr.com/320/240?lock=1159165972"
                        },
                        new
                        {
                            Id = new Guid("6a58d5b2-92db-4890-094e-bc91f1ea68a4"),
                            Code = "West",
                            Name = "Veumside",
                            RegionImageUrl = "https://loremflickr.com/320/240?lock=1639072835"
                        },
                        new
                        {
                            Id = new Guid("29500c13-ffb9-6194-63d6-52daf930f59f"),
                            Code = "West",
                            Name = "Gorczanystad",
                            RegionImageUrl = "https://loremflickr.com/320/240?lock=726986386"
                        });
                });

            modelBuilder.Entity("NZwalks.Models.Walks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc7b775b-57c1-55b6-c25d-3fc5c24b1ab2"),
                            Description = "Vel voluptas dolorum maiores accusamus quo ut deserunt hic quidem.",
                            DifficultyId = new Guid("5895a33b-fafc-4798-9688-2c609d097fe6"),
                            LengthInKm = 32.0,
                            Name = "Violet Summit",
                            RegionId = new Guid("176e331a-4eff-ee98-ea56-dc4a0e84757d")
                        },
                        new
                        {
                            Id = new Guid("d8b1d412-edae-3c3d-aa0e-13f59a346ea9"),
                            Description = "Sed provident laudantium nam dicta sequi voluptas quasi officia non.",
                            DifficultyId = new Guid("0c306fab-d484-41fe-9a44-d6088bb75daf"),
                            LengthInKm = 26.0,
                            Name = "Toy Creek",
                            RegionId = new Guid("176e331a-4eff-ee98-ea56-dc4a0e84757d")
                        },
                        new
                        {
                            Id = new Guid("edb32f54-419a-eb03-5377-fddcd2497cbc"),
                            Description = "Molestias nesciunt animi expedita ut distinctio blanditiis sunt eum dolorem.",
                            DifficultyId = new Guid("5895a33b-fafc-4798-9688-2c609d097fe6"),
                            LengthInKm = 2.0,
                            Name = "Terry Station",
                            RegionId = new Guid("97930e56-f26e-611e-1820-46d1a0245995")
                        },
                        new
                        {
                            Id = new Guid("6aa0cc72-8081-420f-30c0-de4b3678a3ef"),
                            Description = "In enim officia nihil dolorem mollitia officiis id occaecati id.",
                            DifficultyId = new Guid("42d731f8-d04e-4633-9c4f-1a4a27500b55"),
                            LengthInKm = 29.0,
                            Name = "Rosenbaum Island",
                            RegionId = new Guid("4d05aca1-c10a-5317-bfe4-8c17096cb62a")
                        },
                        new
                        {
                            Id = new Guid("056994e3-11a9-493b-f6ae-550ff700a807"),
                            Description = "Aut ut eos cum voluptatem deleniti rem qui velit sit.",
                            DifficultyId = new Guid("42d731f8-d04e-4633-9c4f-1a4a27500b55"),
                            LengthInKm = 2.0,
                            Name = "Tyson Motorway",
                            RegionId = new Guid("97930e56-f26e-611e-1820-46d1a0245995")
                        },
                        new
                        {
                            Id = new Guid("a2683ee5-9e0f-d546-e376-aba2bf6887e2"),
                            Description = "Eius sunt facere et consectetur ut sed sint voluptatum quasi.",
                            DifficultyId = new Guid("42d731f8-d04e-4633-9c4f-1a4a27500b55"),
                            LengthInKm = 23.0,
                            Name = "Fatima Rue",
                            RegionId = new Guid("4d05aca1-c10a-5317-bfe4-8c17096cb62a")
                        },
                        new
                        {
                            Id = new Guid("b829df0d-0698-f9f8-698c-0f7b45769eec"),
                            Description = "Mollitia quo odit aut est qui aut architecto enim velit.",
                            DifficultyId = new Guid("42d731f8-d04e-4633-9c4f-1a4a27500b55"),
                            LengthInKm = 2.0,
                            Name = "Valerie Green",
                            RegionId = new Guid("176e331a-4eff-ee98-ea56-dc4a0e84757d")
                        },
                        new
                        {
                            Id = new Guid("df94653f-ce3e-2549-6ecd-88cad731ad04"),
                            Description = "Est hic debitis consequatur error sint ad iusto corporis doloremque.",
                            DifficultyId = new Guid("0c306fab-d484-41fe-9a44-d6088bb75daf"),
                            LengthInKm = 21.0,
                            Name = "Denesik Turnpike",
                            RegionId = new Guid("6a58d5b2-92db-4890-094e-bc91f1ea68a4")
                        },
                        new
                        {
                            Id = new Guid("df3bbb41-bee1-cbae-5b5a-3d1c2454275e"),
                            Description = "Exercitationem et reprehenderit aut natus cum beatae ullam nemo molestias.",
                            DifficultyId = new Guid("0c306fab-d484-41fe-9a44-d6088bb75daf"),
                            LengthInKm = 3.0,
                            Name = "Delphia Common",
                            RegionId = new Guid("97930e56-f26e-611e-1820-46d1a0245995")
                        },
                        new
                        {
                            Id = new Guid("1b88ddc1-cef5-ae22-1522-8ab44d403b6b"),
                            Description = "Itaque quaerat suscipit sed veniam reiciendis et odit facilis qui.",
                            DifficultyId = new Guid("42d731f8-d04e-4633-9c4f-1a4a27500b55"),
                            LengthInKm = 2.0,
                            Name = "Little Curve",
                            RegionId = new Guid("4d05aca1-c10a-5317-bfe4-8c17096cb62a")
                        },
                        new
                        {
                            Id = new Guid("475ac313-0ccc-f968-ffe8-16addb9167c8"),
                            Description = "Ex occaecati ad occaecati est praesentium ullam tenetur dolorem quo.",
                            DifficultyId = new Guid("0c306fab-d484-41fe-9a44-d6088bb75daf"),
                            LengthInKm = 31.0,
                            Name = "Gulgowski Lake",
                            RegionId = new Guid("97930e56-f26e-611e-1820-46d1a0245995")
                        },
                        new
                        {
                            Id = new Guid("89a056fd-f3e5-f69f-6063-bd74ca2d01e5"),
                            Description = "Velit commodi ratione voluptas sit quia dicta maxime placeat pariatur.",
                            DifficultyId = new Guid("5895a33b-fafc-4798-9688-2c609d097fe6"),
                            LengthInKm = 14.0,
                            Name = "Susie Lodge",
                            RegionId = new Guid("4d05aca1-c10a-5317-bfe4-8c17096cb62a")
                        },
                        new
                        {
                            Id = new Guid("85b09ada-def0-06e2-131a-7c67cba917d4"),
                            Description = "Autem ut quo aut accusamus dolor consectetur provident sunt fugiat.",
                            DifficultyId = new Guid("42d731f8-d04e-4633-9c4f-1a4a27500b55"),
                            LengthInKm = 10.0,
                            Name = "Amir Stravenue",
                            RegionId = new Guid("29500c13-ffb9-6194-63d6-52daf930f59f")
                        },
                        new
                        {
                            Id = new Guid("2f993461-7b7d-40f4-2cad-d86dcc02befd"),
                            Description = "Accusantium fuga explicabo hic recusandae sint incidunt aliquid dolores et.",
                            DifficultyId = new Guid("0c306fab-d484-41fe-9a44-d6088bb75daf"),
                            LengthInKm = 28.0,
                            Name = "Schuster Glen",
                            RegionId = new Guid("29500c13-ffb9-6194-63d6-52daf930f59f")
                        },
                        new
                        {
                            Id = new Guid("9706158a-e70f-2f57-cb0f-bb154984e8e8"),
                            Description = "Unde reprehenderit accusamus deserunt amet itaque provident dolores tempore ea.",
                            DifficultyId = new Guid("5895a33b-fafc-4798-9688-2c609d097fe6"),
                            LengthInKm = 10.0,
                            Name = "Balistreri Port",
                            RegionId = new Guid("4d05aca1-c10a-5317-bfe4-8c17096cb62a")
                        },
                        new
                        {
                            Id = new Guid("b7e34453-27fc-7aed-1a44-db9b5db16e22"),
                            Description = "Minima odit nisi sunt aliquam qui nemo laboriosam veniam facere.",
                            DifficultyId = new Guid("5895a33b-fafc-4798-9688-2c609d097fe6"),
                            LengthInKm = 4.0,
                            Name = "Fritsch Route",
                            RegionId = new Guid("29500c13-ffb9-6194-63d6-52daf930f59f")
                        },
                        new
                        {
                            Id = new Guid("04c105c9-31a1-30ec-f890-20c60e21e9bb"),
                            Description = "Harum error magnam cupiditate in enim ut qui facere perspiciatis.",
                            DifficultyId = new Guid("5895a33b-fafc-4798-9688-2c609d097fe6"),
                            LengthInKm = 17.0,
                            Name = "Mertz Plain",
                            RegionId = new Guid("29500c13-ffb9-6194-63d6-52daf930f59f")
                        },
                        new
                        {
                            Id = new Guid("58d12af7-69ef-e181-c452-1cdafdc19336"),
                            Description = "Qui blanditiis ut est doloremque eius et consequatur iusto quod.",
                            DifficultyId = new Guid("5895a33b-fafc-4798-9688-2c609d097fe6"),
                            LengthInKm = 28.0,
                            Name = "Spinka Road",
                            RegionId = new Guid("4d05aca1-c10a-5317-bfe4-8c17096cb62a")
                        },
                        new
                        {
                            Id = new Guid("e3cedb76-9150-0acb-e38d-6e45137038fa"),
                            Description = "Fugiat aspernatur tempore in doloremque eveniet molestias omnis voluptates recusandae.",
                            DifficultyId = new Guid("42d731f8-d04e-4633-9c4f-1a4a27500b55"),
                            LengthInKm = 37.0,
                            Name = "Kenya Roads",
                            RegionId = new Guid("97930e56-f26e-611e-1820-46d1a0245995")
                        },
                        new
                        {
                            Id = new Guid("2163e51e-aff2-43e6-a3af-18daacd38549"),
                            Description = "Voluptatem eveniet omnis soluta sed natus et minima id est.",
                            DifficultyId = new Guid("42d731f8-d04e-4633-9c4f-1a4a27500b55"),
                            LengthInKm = 35.0,
                            Name = "Lonnie Curve",
                            RegionId = new Guid("97930e56-f26e-611e-1820-46d1a0245995")
                        });
                });

            modelBuilder.Entity("NZwalks.Models.Walks", b =>
                {
                    b.HasOne("NZwalks.Models.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZwalks.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
